### ISSUE TITLE
JavaScript errors from Livewire break interactive functionality like search

### ISSUE THREAD

**Issue by tobias-grasse** [blade-ui-kit/blade-ui-kit.com#125]
### Description:
On load of the [icon search page](https://blade-ui-kit.com/blade-icons#search), the browser console throws two errors that break all JavaScript functionality on the site, notably the icon search. The `Livewire is not a constructor` error occurs on all other pages as well.

### Steps To Reproduce:
1. Open https://blade-ui-kit.com/blade-icons#search in a browser (tested in Arc, Safari and Firefox Developer Edition on macOS)
2. Select an icon package from the list
3. See error: The icon count + text in the search field placeholder does not update
4. Enter search term
5. See error: The result list does not update

The browser console shows the following errors:
```
Uncaught TypeError: Livewire is not a constructor
    <anonymous> https://blade-ui-kit.com/blade-icons#search:1761

Uncaught Snapshot missing on Livewire component with id: gnWxIAhPM9z7ECtp0kud
```
![image](https://github.com/blade-ui-kit/blade-ui-kit.com/assets/834914/b76d6acb-60c5-4b20-a53c-860b96c59014)

**Comment by driesvints** [comment]
Thanks. Please see https://twitter.com/driesvints/status/1759530073240015359 as I have no idea how to solve this one.

**Comment by driesvints** [comment]
@tobias-grasse @bfarrgaynor @nizzam does it work again for you all? Make sure to try a hard refresh or try a private browser window.

**Comment by tobias-grasse** [comment]
@driesvints Works again, thank you very much!

**Comment by nizzam** [comment]
Working well now.
Thank you for the follow-up 👍

**Comment by bfarrgaynor** [comment]
Confirmed working. Safe to close issue.

**Comment by driesvints** [comment]
Thanks all!
