### ISSUE TITLE
Can't use all icons from blade-ui kit in laravel 11

### ISSUE THREAD

**Issue by adnanerlansyah403** [blade-ui-kit/blade-ui-kit.com#130]
- Library Version: ^3.3
- Laravel Version: 11
- PHP Version: 8.2

### Description:
All icons from blade-ui kit doesn't work

### Steps To Reproduce:
- Install Laravel 11
- Install blade-ui kit
- Try to use one icon from blade-ui

**Comment by driesvints** [comment]
Please don't report this on multiple repos.
