### ISSUE TITLE
Add HeroiconsV2 to the icon search

### ISSUE THREAD

**Issue by Mondotosz** [blade-ui-kit/blade-ui-kit.com#92]
Heroicons v2 came out 15 days ago and blade-ui-kit/blade-heroicons already released a matching version.

Heroicons v2 changes the visual and the name of many icons as listed [on their release](https://github.com/tailwindlabs/heroicons/releases/tag/v2.0.0), which would lead to confusion when using the icon search on the website.
Since there is a visual change associated with v2, I believe the best choice would be to have both versions appear on the search page.

**Comment by driesvints** [comment]
Yeah I forgot to do this when I released Heroicons v2. I'll take care of this soonish. Thanks

**Comment by driesvints** [comment]
Got that merged.
